package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type Data struct {
	id         int
	first_name string
	last_name  string
	email      string
	gender     string
	ip_address string
}

func Jsonparse(w http.ResponseWriter, r *http.Request) {

	var parsed []Data

	jsonStr := `
		[{
			"id": 1,
			"first_name": "Maximilian",
			"last_name": "Dobney",
			"email": "mdobney0@naver.com",
			"gender": "Male",
			"ip_address": "128.169.191.159"
		}, {
			"id": 2,
			"first_name": "Kathleen",
			"last_name": "Malec",
			"email": "kmalec1@creativecommons.org",
			"gender": "Female",
			"ip_address": "230.165.123.207"
		}, {
			"id": 3,
			"first_name": "Borg",
			"last_name": "Lovekin",
			"email": "blovekin2@patch.com",
			"gender": "Male",
			"ip_address": "232.210.25.39"
		}, {
			"id": 4,
			"first_name": "Darla",
			"last_name": "Btham",
			"email": "dbtham3@businessinsider.com",
			"gender": "Female",
			"ip_address": "129.138.121.135"
		}, {
			"id": 5,
			"first_name": "Lynette",
			"last_name": "Birchett",
			"email": "lbirchett4@mashable.com",
			"gender": "Female",
			"ip_address": "173.138.196.40"
		}, {
			"id": 6,
			"first_name": "Rodrigo",
			"last_name": "Zimmermanns",
			"email": "rzimmermanns5@house.gov",
			"gender": "Male",
			"ip_address": "160.235.107.217"
		}, {
			"id": 7,
			"first_name": "Yul",
			"last_name": "Peter",
			"email": "ypeter6@storify.com",
			"gender": "Male",
			"ip_address": "191.8.201.145"
		}, {
			"id": 8,
			"first_name": "Willie",
			"last_name": "Bauldry",
			"email": "wbauldry7@sun.com",
			"gender": "Male",
			"ip_address": "30.175.195.95"
		}, {
			"id": 9,
			"first_name": "Neron",
			"last_name": "Trees",
			"email": "ntrees8@rambler.ru",
			"gender": "Male",
			"ip_address": "111.29.19.11"
		}, {
			"id": 10,
			"first_name": "Levey",
			"last_name": "McIlvenny",
			"email": "lmcilvenny9@constantcontact.com",
			"gender": "Male",
			"ip_address": "103.32.223.34"
		}, {
			"id": 11,
			"first_name": "Laura",
			"last_name": "Abdy",
			"email": "labdya@cam.ac.uk",
			"gender": "Female",
			"ip_address": "110.135.103.175"
		}, {
			"id": 12,
			"first_name": "Billie",
			"last_name": "Beharrell",
			"email": "bbeharrellb@soup.io",
			"gender": "Male",
			"ip_address": "253.24.247.114"
		}, {
			"id": 13,
			"first_name": "Giustino",
			"last_name": "Toombes",
			"email": "gtoombesc@edublogs.org",
			"gender": "Male",
			"ip_address": "46.199.205.242"
		}, {
			"id": 14,
			"first_name": "Babbette",
			"last_name": "Alfonsetti",
			"email": "balfonsettid@webmd.com",
			"gender": "Female",
			"ip_address": "190.173.223.100"
		}, {
			"id": 15,
			"first_name": "Alanson",
			"last_name": "Blore",
			"email": "abloree@bloglines.com",
			"gender": "Polygender",
			"ip_address": "199.66.104.235"
		}, {
			"id": 16,
			"first_name": "Alastair",
			"last_name": "Vreede",
			"email": "avreedef@php.net",
			"gender": "Male",
			"ip_address": "244.212.93.180"
		}, {
			"id": 17,
			"first_name": "Sharyl",
			"last_name": "Hudleston",
			"email": "shudlestong@posterous.com",
			"gender": "Female",
			"ip_address": "133.252.198.166"
		}, {
			"id": 18,
			"first_name": "Katee",
			"last_name": "Armes",
			"email": "karmesh@about.me",
			"gender": "Female",
			"ip_address": "76.26.217.45"
		}, {
			"id": 19,
			"first_name": "Charlene",
			"last_name": "Koppke",
			"email": "ckoppkei@feedburner.com",
			"gender": "Female",
			"ip_address": "173.168.68.40"
		}, {
			"id": 20,
			"first_name": "Egbert",
			"last_name": "Fry",
			"email": "efryj@ezinearticles.com",
			"gender": "Male",
			"ip_address": "140.228.38.11"
		}, {
			"id": 21,
			"first_name": "Camala",
			"last_name": "Ellwand",
			"email": "cellwandk@elegantthemes.com",
			"gender": "Female",
			"ip_address": "198.220.148.241"
		}, {
			"id": 22,
			"first_name": "Lara",
			"last_name": "Jordon",
			"email": "ljordonl@senate.gov",
			"gender": "Female",
			"ip_address": "241.114.114.58"
		}, {
			"id": 23,
			"first_name": "Maurizio",
			"last_name": "Cameron",
			"email": "mcameronm@devhub.com",
			"gender": "Male",
			"ip_address": "120.221.153.147"
		}, {
			"id": 24,
			"first_name": "Obadias",
			"last_name": "Maryott",
			"email": "omaryottn@senate.gov",
			"gender": "Male",
			"ip_address": "73.59.185.157"
		}, {
			"id": 25,
			"first_name": "Emmalynne",
			"last_name": "Van Hesteren",
			"email": "evanhestereno@multiply.com",
			"gender": "Female",
			"ip_address": "42.184.37.126"
		}, {
			"id": 26,
			"first_name": "Miner",
			"last_name": "Trayling",
			"email": "mtraylingp@wsj.com",
			"gender": "Male",
			"ip_address": "81.181.9.145"
		}, {
			"id": 27,
			"first_name": "Stanislaus",
			"last_name": "Pirolini",
			"email": "spiroliniq@theglobeandmail.com",
			"gender": "Male",
			"ip_address": "200.80.231.12"
		}, {
			"id": 28,
			"first_name": "Corry",
			"last_name": "Salan",
			"email": "csalanr@princeton.edu",
			"gender": "Female",
			"ip_address": "159.245.57.240"
		}, {
			"id": 29,
			"first_name": "Jolene",
			"last_name": "Biskup",
			"email": "jbiskups@squarespace.com",
			"gender": "Female",
			"ip_address": "164.179.131.126"
		}, {
			"id": 30,
			"first_name": "Eamon",
			"last_name": "Garatty",
			"email": "egarattyt@stanford.edu",
			"gender": "Male",
			"ip_address": "94.163.103.155"
		}, {
			"id": 31,
			"first_name": "Bordy",
			"last_name": "Aurelius",
			"email": "baureliusu@msn.com",
			"gender": "Genderfluid",
			"ip_address": "77.47.48.100"
		}, {
			"id": 32,
			"first_name": "Christophe",
			"last_name": "Lante",
			"email": "clantev@amazonaws.com",
			"gender": "Male",
			"ip_address": "109.97.92.92"
		}, {
			"id": 33,
			"first_name": "Gawen",
			"last_name": "Sowter",
			"email": "gsowterw@sogou.com",
			"gender": "Male",
			"ip_address": "227.17.248.164"
		}, {
			"id": 34,
			"first_name": "Mandi",
			"last_name": "Rubenchik",
			"email": "mrubenchikx@drupal.org",
			"gender": "Female",
			"ip_address": "255.137.9.181"
		}, {
			"id": 35,
			"first_name": "Laney",
			"last_name": "Vaszoly",
			"email": "lvaszolyy@si.edu",
			"gender": "Male",
			"ip_address": "19.20.38.203"
		}, {
			"id": 36,
			"first_name": "Bank",
			"last_name": "Simion",
			"email": "bsimionz@alexa.com",
			"gender": "Male",
			"ip_address": "78.98.186.92"
		}, {
			"id": 37,
			"first_name": "Kelila",
			"last_name": "Bannerman",
			"email": "kbannerman10@ehow.com",
			"gender": "Genderfluid",
			"ip_address": "38.194.154.131"
		}, {
			"id": 38,
			"first_name": "Timofei",
			"last_name": "Hammill",
			"email": "thammill11@woothemes.com",
			"gender": "Male",
			"ip_address": "126.28.236.206"
		}, {
			"id": 39,
			"first_name": "Saudra",
			"last_name": "Newns",
			"email": "snewns12@ucoz.ru",
			"gender": "Female",
			"ip_address": "0.153.154.39"
		}, {
			"id": 40,
			"first_name": "Cari",
			"last_name": "Loyley",
			"email": "cloyley13@hhs.gov",
			"gender": "Female",
			"ip_address": "193.163.224.83"
		}, {
			"id": 41,
			"first_name": "Siward",
			"last_name": "Chaulk",
			"email": "schaulk14@who.int",
			"gender": "Genderfluid",
			"ip_address": "98.241.41.88"
		}, {
			"id": 42,
			"first_name": "Karola",
			"last_name": "Karadzas",
			"email": "kkaradzas15@hatena.ne.jp",
			"gender": "Female",
			"ip_address": "134.123.50.127"
		}, {
			"id": 43,
			"first_name": "Fergus",
			"last_name": "Gergler",
			"email": "fgergler16@cnbc.com",
			"gender": "Male",
			"ip_address": "170.239.112.208"
		}, {
			"id": 44,
			"first_name": "Ulberto",
			"last_name": "McMyler",
			"email": "umcmyler17@youtu.be",
			"gender": "Male",
			"ip_address": "249.89.255.65"
		}, {
			"id": 45,
			"first_name": "Corrinne",
			"last_name": "Arnholdt",
			"email": "carnholdt18@virginia.edu",
			"gender": "Female",
			"ip_address": "81.55.105.159"
		}, {
			"id": 46,
			"first_name": "Fernande",
			"last_name": "Anchor",
			"email": "fanchor19@photobucket.com",
			"gender": "Female",
			"ip_address": "125.182.221.217"
		}, {
			"id": 47,
			"first_name": "Marice",
			"last_name": "Gumary",
			"email": "mgumary1a@godaddy.com",
			"gender": "Female",
			"ip_address": "159.56.38.182"
		}, {
			"id": 48,
			"first_name": "Jorge",
			"last_name": "Barclay",
			"email": "jbarclay1b@scientificamerican.com",
			"gender": "Male",
			"ip_address": "57.1.79.17"
		}, {
			"id": 49,
			"first_name": "Kaleena",
			"last_name": "Goward",
			"email": "kgoward1c@youtube.com",
			"gender": "Female",
			"ip_address": "212.37.10.40"
		}, {
			"id": 50,
			"first_name": "Aline",
			"last_name": "Duiged",
			"email": "aduiged1d@gizmodo.com",
			"gender": "Female",
			"ip_address": "161.245.118.63"
		}]
	`
	// data := map[string]interface{}{}
	start := time.Now()
	json.Unmarshal([]byte(jsonStr), &parsed)
	duration := time.Since(start)

	// fmt.Fprintf(w, "len=%d cap=%d %v\n", len(s), cap(s), s)
	fmt.Fprintf(w, "%f ms", float64(duration.Nanoseconds())/1000000)
}
